// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deck } from "./Deck";
import type { PointsHistogramBucket } from "./PointsHistogramBucket";

export type AnalyzedDeckWithSource = { url_source: string | null, deck: Deck, total_points: string, histogram: Array<PointsHistogramBucket>, };
