// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardRating = { uuid: string, card_oracle_id: string, rater_person_uuid: string, points: string, reason: string | null, };
