// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The legality of a Magic: The Gathering card.
 *
 * Restricted is very unlikely - probably impossible.
 * Non legal cards will not be listed.
 */
export type CardLegality = "legal" | "restricted" | "banned";
