// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardLegality } from "./CardLegality";

/**
 * A Magic: The Gathering card.
 */
export type Card = { 
/**
 * A unique identifier for the mechanics / behavior of the card
 */
oracle_id: string, 
/**
 * The name of the card
 */
name: string, 
/**
 * An image uri for the card
 */
image_uri: string | null, 
/**
 * The legality of the card
 */
legality: CardLegality, };
