// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardWithGlobalPoints } from "./CardWithGlobalPoints";

export type Deck = { commanders: Array<CardWithGlobalPoints>, maindeck: Array<CardWithGlobalPoints>, };
