// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetCardsParamsSort } from "./GetCardsParamsSort";

export type GetCardsParams = { q: string | null, sort: GetCardsParamsSort | null, page: number, page_size: number, };
