// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetPersonsParamsSort } from "./GetPersonsParamsSort";

/**
 * Query parameters used for getting persons
 */
export type GetPersonsParams = { 
/**
 * Gets all persons who are following a specific person
 */
person_following: string | null, 
/**
 * Gets all persons who are followed by a specific person
 */
person_followee: string | null, 
/**
 * Queries people by their username
 */
q: string | null, 
/**
 * How to sort the result
 */
sort: GetPersonsParamsSort | null, 
/**
 * Pagination parameter
 */
page: number, 
/**
 * Size of the page
 */
page_size: number, };
