// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetPersonsParamsSort } from "./GetPersonsParamsSort";

export type GetPersonsParams = { q: string | null, sort: GetPersonsParamsSort | null, page: number, page_size: number, };
