// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetRatingsParamsSort = "liked" | "disliked" | "controversial" | "recent" | "highest_rated" | "lowest_rated";
