// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetTrackedDecksParamsSort } from "./GetTrackedDecksParamsSort";

export type GetTrackedDecksParams = { tracker_person_uuid: string | null, q: string | null, sort: GetTrackedDecksParamsSort | null, page: number, page_size: number, };
