// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetTrackedDecksParamsSort = "recent" | "most_points" | "least_points" | "most_personal_points" | "least_personal_points";
