// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HomeMetrics = { total_cards_rated: number, total_persons: number, total_ratings: number, };
