// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A base person enriched with metrics and follow information
 */
export type PersonEnriched = { 
/**
 * How many followers this person has
 */
followers: number, 
/**
 * How many people this person is following
 */
following: number, 
/**
 * How many likes across all ratings this person has received
 */
likes: number, 
/**
 * How many dislikes across all ratings this person has received
 */
dislikes: number, 
/**
 * How many cards this person has rated
 */
cards_rated: number, 
/**
 * How many decks this person is tracking
 */
tracked_decks: number, 
/**
 * If authenticated, if the current user is following this person
 */
am_following: boolean | null, 
/**
 * If the `person_following` was passed, this is the date this person has started following that person
 */
started_following: string | null, 
/**
 * If the `person_followee` was passed, this is the date this person was followed by that person
 */
followed_on: string | null, uuid: string, username: string, picture_url: string | null, created_at: string, updated_at: string | null, };
