// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Person = { uuid: string, username: string, picture_url: string | null, created_at: string, updated_at: string | null, };
