// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bucket that holds a range of points and the number of elements
 * in that range to make up a histogram.
 */
export type PointsHistogramBucket = { lower_inclusive_points_bound: string, upper_exclusive_points_bound: string, count: number, };
