// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeckUrl } from "./DeckUrl";
import type { Decklist } from "./Decklist";

export type PostAnalyzeBody = { "type": "url" } & DeckUrl | { "type": "decklist" } & Decklist;
