// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyzedDeck } from "./AnalyzedDeck";
import type { PostAnalyzeInvalidCards } from "./PostAnalyzeInvalidCards";

export type PostAnalyzeDeckResponse = { "type": "valid" } & AnalyzedDeck | { "type": "invalid" } & PostAnalyzeInvalidCards;
