// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for following or unfollowing a person
 */
export type PostFollowPersonBody = { 
/**
 * Who needs to be followed or unfollowed
 */
followed_person_uuid: string, };
