// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deck } from "./Deck";
import type { PostAnalyzeBody } from "./PostAnalyzeBody";

export type PostAnalyzeDeckResponse = { source: PostAnalyzeBody, deck: Deck, total_points: string, };
