// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PutRatingBody = { card_oracle_id: string, points: string, reason: string | null, };
