// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RatingHistogramBucket = { lower_inclusive_points_bound: string, upper_exclusive_points_bound: string, count: number, };
