// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackedDeckCardType } from "./TrackedDeckCardType";

/**
 * A card in a tracked deck.
 */
export type TrackedDeckCard = { uuid: string, tracked_deck_uuid: string, ty: TrackedDeckCardType, count: number, card_oracle_id: string, };
