// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackedDeckWithTotalPoints = { total_global_points: string, total_personal_points: string, uuid: string, tracker_person_uuid: string, name: string, url_source: string | null, created_at: string, updated_at: string | null, };
