// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tracked deck
 */
export type TrackedDeck = { uuid: string, tracker_person_uuid: string, name: string, url_source: string | null, created_at: string, updated_at: string | null, last_synced: string, };
