// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of card in a tracked deck.
 *
 * This is used to distinguish between commander and maindeck cards.
 * (in the future, partners if I ever get around to it)
 */
export type TrackedDeckCardType = "commander" | "maindeck";
