- name: Set up postgres service
  import_playbook: services/postgres.yml

- name: Set up controlmylights service
  import_playbook: services/controlmylights.yml

- name: Set up the_peoples_edh_bracket service
  import_playbook: services/the_peoples_edh_bracket.yml
