on:
  workflow_call: {}
  workflow_dispatch: {}
  
jobs:
  build_server:
    name: 🔨 Build controlmylights server
    runs-on: ubuntu-latest
    steps:
      # TODO: Need to check out every rust project atm, need to find
      # a way to seperate rust projects or build up the list dynamically
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
<<<<<<< HEAD
=======
            public/package.json
>>>>>>> f38e48a81f79fad7a8cb26d212ee899ac83390bc
            public/pnpm-lock.yaml
            public/pnpm-workspace.yaml
            public/Cargo.toml
            public/Cargo.lock
            public/apps
            public/libs

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: public/package.json
          run_install: |
            - cwd: ./public
              args: [--frozen-lockfile, --filter, "controlmylightsclient"]

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-controlmylightsv2-${{ hashFiles('public/Cargo.lock') }}

      - run: cargo build --verbose --release --locked
        working-directory: ./public/apps/controlmylights/controlmylights_server

      - uses: actions/upload-artifact@v4
        with:
          name: controlmylights_server
          path: ./public/target/release/controlmylights_server

  deploy:
    name: 🚀 Deploy controlmylights server
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - build_server
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: controlmylights_server

      - name: Upload new binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: btarr.xyz
          username: deployer
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          source: ./controlmylights_server
          target: /tmp/controlmylights/
          overwrite: true

      - name: Install new binary and restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: btarr.xyz
          username: deployer
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          script: |
            set -eu
            sudo mkdir -p /opt/controlmylights/bin
            sudo install -m 755 /tmp/controlmylights/controlmylights_server /opt/controlmylights/bin/controlmylights
            rm -rf /tmp/controlmylights
            sudo systemctl restart controlmylights.service
            sudo systemctl is-active controlmylights.service
  