name: Build 🔨 & Deploy 🚀 StackTask

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: apps/StackTask

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: |
            - cwd: ./apps/StackTask
              args: [--frozen-lockfile]

      - run: pnpm build
        working-directory: ./apps/StackTask

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./apps/StackTask/dist

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload new app
        uses: appleboy/scp-action@v0.1.7
        with:
          host: btarr.xyz # TODO: How do I propagate IP instead of relying on DNS
          username: deployer
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          source: ./dist/*
          target: /var/www/stacktask.btarr.xyz/
          overwrite: true
          strip_components: 1

      - name: Make executable
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: btarr.xyz # TODO: How do I propagate IP instead of relying on DNS
          username: deployer
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          script: sudo chmod -R a+rX /var/www/stacktask.btarr.xyz
