on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build:
    name: 🔨 Build StackTask
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            public/package.json
            public/pnpm-lock.yaml
            public/pnpm-workspace.yaml
            public/apps/StackTask

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - cwd: ./public
              args: [--frozen-lockfile]

      - run: pnpm build
        working-directory: ./public/apps/StackTask

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./public/apps/StackTask/dist

  deploy:
    name: 🚀 Deploy StackTask
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload new app
        uses: appleboy/scp-action@v0.1.7
        with:
          host: btarr.xyz
          username: deployer
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          source: ./dist/*
          target: /tmp/stacktask.btarr.xyz/
          overwrite: true
          strip_components: 1

      - name: Swap new app into place
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: btarr.xyz
          username: deployer
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          script: |
            set -eu
            sudo mkdir -p /var/www/stacktask.btarr.xyz
            sudo rsync -a --delete /tmp/stacktask.btarr.xyz/ /var/www/stacktask.btarr.xyz/
            sudo find /var/www/stacktask.btarr.xyz -type d -exec chmod 755 {} \;
            sudo find /var/www/stacktask.btarr.xyz -type f -exec chmod 644 {} \;
            rm -rf /tmp/stacktask.btarr.xyz
