on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy 🚀 Terraform Backend 🪣
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: services/terraform-backend

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - run: npm install -g aws-cdk

      - run: pnpm install
        working-directory: services/terraform-backend

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOYER_AWS_ROLE_ARN }}
          aws-region: us-west-1

      - run: cdk deploy --require-approval never
        working-directory: services/terraform-backend
